apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: This task will clean up a workspace by deleting all the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: MORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${MORKSPACE_SOURCE_PATH} ..."
        # Delete any existing contents of the directory if it exists.
        #
        # We don't just "rm -rf ${MORKSPACE_SOURCE_PATH}" because ${MORKSPACE_SOURCE_PATH}
        # might be misconfigured and point to / or the root of a mounted volume.
        if [ -d "${MORKSPACE_SOURCE_PATH}" ]; then
          # Delete non-hidden files and directories
          rm -rf "${MORKSPACE_SOURCE_PATH:?}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${MORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${MORKSPACE_SOURCE_PATH}"/..?*
        fi
---        
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  description: "Ejecuta pruebas de Python con nosetests."
  workspaces:
    - name: source
  params:
    - name: args
      description: "Argumentos para nosetests"
      type: string
      default: "--v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)        